on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Host Bot VM
    runs-on: self-hosted # Utilise ton runner auto-hébergé
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.1.37 >> ~/.ssh/known_hosts

      - name: Copy files to VM
        run: |
          scp -r ./ pims@192.168.1.37:/bot/kodyborg/

      - name: Install dependencies and start bot
        run: |
          ssh pims@192.168.1.37 "
          cd /bot/kodyborg &&
          bun install &&
          nohup bun run start > bot.log 2>&1 && echo 'Bot started successfully!' || echo 'Failed to start bot'"
